dbt_tf:
  outputs:
    dev_stg:
      account: LXYUPGO-WC96196
      database: dev_db
      password: Hakkoda@1234567890
      role: ACCOUNTADMIN
      schema: TRANSFORM_SCH
      threads: 8
      type: snowflake
      user: ADMIN
      warehouse: TRANSFORM_WH
  target: dev_stg
    dev_mrt:
      account: LXYUPGO-WC96196
      database: dev_db
      password: Hakkoda@1234567890
      role: ACCOUNTADMIN
      schema: MART_SCH
      threads: 8
      type: snowflake
      user: ADMIN
      warehouse: TRANSFORM_WH
  target: dev_mrt
