dbt_tf:
  target: dev_stg   # default target when you run dbt commands

  outputs:
    dev_stg:
      type: snowflake
      account: LXYUPGO-WC96196
      user: ADMIN
      password: Hakkoda@1234567890
      role: ACCOUNTADMIN
      warehouse: TRANSFORM_WH
      database: dev_db
      threads: 8

    dev_mrt:
      type: snowflake
      account: LXYUPGO-WC96196
      user: ADMIN
      password: Hakkoda@1234567890
      role: ACCOUNTADMIN
      warehouse: TRANSFORM_WH
      database: dev_db
      threads: 8
